# Generated by Django 3.0.5 on 2020-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='endereco',
            field=models.CharField(default=212, max_length=200),
            preserve_default=False,
        ),
    ]
