# Generated by Django 3.0.5 on 2020-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0002_list_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='nro_whatsapp',
            field=models.CharField(default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='sobrenome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
