# Generated by Django 3.0.5 on 2020-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0006_auto_20200409_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='complemento',
            field=models.TextField(default='NA'),
        ),
    ]
