# Generated by Django 3.0.5 on 2020-04-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0008_auto_20200409_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='complemento',
            field=models.CharField(blank=True, default='NA', max_length=200, null=True),
        ),
    ]
