# Generated by Django 3.0.5 on 2020-04-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0013_auto_20200414_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='id',
        ),
        migrations.RemoveField(
            model_name='list2',
            name='id',
        ),
        migrations.AddField(
            model_name='list',
            name='comentario1',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='comentario2',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='conexao_whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list2',
            name='comentario1',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list2',
            name='comentario2',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='list2',
            name='conexao_whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='nro_whatsapp',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='list2',
            name='nro_whatsapp',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
