# Generated by Django 3.0.5 on 2020-04-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0014_auto_20200415_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list2',
            name='id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
