# Generated by Django 3.0.5 on 2020-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0015_auto_20200415_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list2',
            name='id',
            field=models.BooleanField(default=False),
        ),
    ]
