# Generated by Django 3.0.5 on 2020-04-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0016_auto_20200415_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='list',
            name='nro_whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='list2',
            name='nro_whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
