# Generated by Django 3.0.5 on 2020-04-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0017_auto_20200415_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='list',
            name='comentario2',
        ),
        migrations.RemoveField(
            model_name='list',
            name='conexao_whatsapp',
        ),
        migrations.RemoveField(
            model_name='list2',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='list2',
            name='comentario2',
        ),
        migrations.RemoveField(
            model_name='list2',
            name='conexao_whatsapp',
        ),
    ]
