# Generated by Django 3.0.5 on 2020-04-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('nome', models.CharField(default='', max_length=200)),
                ('item', models.CharField(default='', max_length=200)),
                ('sobrenome', models.CharField(default='', max_length=200)),
                ('nro_whatsapp', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('tipo_logradouro', models.CharField(default='', max_length=200)),
                ('endereco', models.CharField(default='', max_length=200)),
                ('complemento', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('bairro', models.CharField(default='', max_length=200)),
                ('estado', models.CharField(default='', max_length=200)),
                ('cidade', models.CharField(default='', max_length=200)),
                ('CEP', models.CharField(default='', max_length=200)),
                ('compras_supermercados', models.BooleanField(default=False)),
                ('compras_farmacia', models.BooleanField(default=False)),
                ('passeio_pet', models.BooleanField(default=False)),
                ('outras_ajudas', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('radio_dist1', models.BooleanField(default=False)),
                ('radio_dist2', models.BooleanField(default=False)),
                ('radio_dist3', models.BooleanField(default=False)),
                ('radio_dist4', models.BooleanField(default=False)),
                ('conexao', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('comentario1', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('comentario2', models.TextField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List2',
            fields=[
                ('item', models.CharField(default='', max_length=200)),
                ('nome', models.CharField(default='', max_length=200)),
                ('sobrenome', models.CharField(default='', max_length=200)),
                ('nro_whatsapp', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('tipo_logradouro', models.CharField(default='', max_length=200)),
                ('endereco', models.CharField(default='', max_length=200)),
                ('complemento', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('bairro', models.CharField(default='', max_length=200)),
                ('estado', models.CharField(default='', max_length=200)),
                ('cidade', models.CharField(default='', max_length=200)),
                ('CEP', models.CharField(default='', max_length=200)),
                ('compras_supermercados', models.BooleanField(default=False)),
                ('compras_farmacia', models.BooleanField(default=False)),
                ('passeio_pet', models.BooleanField(default=False)),
                ('outras_ajudas', models.BooleanField(default=False)),
                ('outras_ajudas_conteudo', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('conexao', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('comentario1', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('comentario2', models.TextField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
