# Generated by Django 3.0.5 on 2020-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0003_auto_20200408_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='CEP',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='bairro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='cidade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='complemento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='compras_farmacia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='compras_supermercados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='estado',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='outras_ajudas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='passeio_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='tipo_logradouro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='endereco',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='nro_whatsapp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='sobrenome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
