# Generated by Django 3.0.5 on 2020-04-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0005_auto_20200409_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='complemento',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='email',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
