# Generated by Django 3.0.5 on 2020-04-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0009_auto_20200409_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='List2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=200)),
                ('nome', models.CharField(default='', max_length=200)),
                ('sobrenome', models.CharField(default='', max_length=200)),
                ('nro_whatsapp', models.CharField(default='', max_length=200)),
                ('email', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('tipo_logradouro', models.CharField(default='', max_length=200)),
                ('endereco', models.CharField(default='', max_length=200)),
                ('complemento', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('bairro', models.CharField(default='', max_length=200)),
                ('estado', models.CharField(default='', max_length=200)),
                ('cidade', models.CharField(default='', max_length=200)),
                ('CEP', models.CharField(default='', max_length=200)),
                ('compras_supermercados', models.BooleanField(default=False)),
                ('compras_farmacia', models.BooleanField(default=False)),
                ('passeio_pet', models.BooleanField(default=False)),
                ('outras_ajudas', models.BooleanField(default=False)),
                ('outras_ajudas_conteudo', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
