# Generated by Django 3.0.5 on 2020-04-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0011_auto_20200414_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='raio1',
        ),
        migrations.RemoveField(
            model_name='list',
            name='raio2',
        ),
        migrations.RemoveField(
            model_name='list',
            name='raio3',
        ),
        migrations.RemoveField(
            model_name='list',
            name='raio4',
        ),
    ]
